apiVersion: v1
kind: Service
metadata:
  name: unreal
spec:
  type: NodePort
  ports:
    - name: irc
      protocol: TCP
      port: 7767
      nodePort: 6667
    - name: ircs
      protocol: TCP
      port: 7769
      nodePort: 6669
  selector:
    name: unreal
