- hosts:
    - base
  roles:
    - base

- hosts:
    - influx
  roles:
    - influx

- hosts:
    - owned
  roles:
    - owned

- hosts:
    - phab
  roles:
    - phab

- hosts:
    - prom
  roles:
    - prom
