- name: install php
  become: yes
  apt:
    name={{ item }}
    state=present
    install_recommends=no
  with_items:
    - php
    - php-mysql
    - php-gd
    - php-curl
    - php-cli
    - php-json
    - php-mbstring
    - mysql-server
    - git
    - php-fpm
    - python-pygments

- name: phabricator user
  become: yes
  user:
    name=phab
    system=yes

- name: phabricator install directory
  become: yes
  file:
    path=/opt/phabricator
    state=directory
    mode="u=rwX,g=rX,o=rX"

- name: libphutil install
  git:
    repo=https://github.com/phacility/libphutil.git
    dest=/opt/phabricator/libphutil
    version=stable
    umask=0022
  become: yes
  notify:
    - restart php-fpm
    - restart phabricator-daemon

- name: phabricator install
  git:
    repo=https://github.com/phacility/phabricator.git
    dest=/opt/phabricator/phabricator
    version=stable
    umask=0022
  become: yes
  notify:
    - restart php-fpm
    - restart phabricator-daemon

- name: arcanist install
  git:
    repo=https://github.com/phacility/arcanist.git
    dest=/opt/phabricator/arcanist
    version=stable
    umask=0022
  become: yes

- set_fact:
    phab_services:
      - phabricator-daemon.service

- name: copy services
  become: yes
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }}
  with_items: "{{ phab_services }}"
  notify:
    - reload systemd
    - restart phabricator-daemon

- name: install services
  become: yes
  command: systemctl enable {{ item }} creates=/etc/systemd/system/multi-user.target.wants/{{ item }}
  with_items: "{{ phab_services }}"

- name: php-fpm overrides directory
  become: yes
  file:
    path=/etc/systemd/system/php7.0-fpm.service.d/
    state=directory

- name: php-fpm hardening
  become: yes
  copy:
    src=systemd-php-fpm-overrides.conf
    dest=/etc/systemd/system/php7.0-fpm.service.d/hardening.conf
  notify:
    - reload systemd
    - restart php-fpm

- name: fpm config for phab
  become: yes
  copy:
    src=phab-fpm.conf
    dest=/etc/php/7.0/fpm/pool.d/phab-fpm.conf
  notify:
    - restart php-fpm

- name: nginx triggers
  become: yes
  file:
    name=/srv/phabricator.goeswhere.com
    state=directory

- name: nginx fragment
  become: yes
  copy:
    src=phab-nginx.frag
    dest=/srv/.phabricator.goeswhere.com.nginx

- name: phabricator filesystem config directory
  become: yes
  file:
    path=/opt/phabricator/phabricator/conf/local
    state=directory
    owner=root
    group=phab
    mode="u=rwX,g=rX,o="

# CREATE USER phab IDENTIFIED BY '..';
# GRANT ALL PRIVILEGES ON `phabricator_%`.* TO 'phab';

- name: repo dir
  become: yes
  file:
    path=/var/repo
    state=directory
    owner=phab
    group=phab
    mode="u=rwX,g=rX,o="
