- name: work dir
  become: yes
  file:
    name=/var/lib/node-exporter
    state=directory
    owner=prom-exporter

#- name: node exporter unit
#  become: yes
#  systemd_unit: src=prometheus-node-exporter.service
