- name: users
  become: yes
  user: name={{ item }} system=yes
  with_items:
    - prom-exporter

- name: custom groups
  become: yes
  group: name={{ item }}
  with_items:
    # TODO
    - can-ssh

- name: copy binaries
  become: yes
  copy:
    src={{ item }}
    dest=/usr/local/bin/{{ item }}
    mode=a+rx
  with_items:
    - node_exporter

- include: exporters.yml
