global:
  scrape_interval:     30s

  external_labels:
    monitor: '{{ inventory_hostname_short }}'

rule_files:
  - alerts.conf

scrape_configs:
  - job_name: prometheus

    scrape_interval: 5s

    static_configs:
      - targets:
        - localhost:9090

    relabel_configs:
      - action: replace
        source_labels: ['__address__']
        target_label: node
        regex: ".*"
        replacement: "{{ inventory_hostname_short }}"


  - job_name: alertmanager

    metrics_path: /alert-manager/metrics

    scrape_interval: 5s

    static_configs:
      - targets:
        - localhost:9093

    relabel_configs:
      - action: replace
        source_labels: ['__address__']
        target_label: node
        regex: ".*"
        replacement: "{{ inventory_hostname_short }}"
