global:
  scrape_interval:     30s

  external_labels:
    monitor: '{{ inventory_hostname_short }}'

rule_files:
  - alerts.conf

scrape_configs:
  - job_name: prometheus

    scrape_interval: 5s

    static_configs:
      - targets:
        - localhost:9090

    relabel_configs:
      - action: replace
        source_labels: ['__address__']
        target_label: node
        regex: ".*"
        replacement: "{{ inventory_hostname_short }}"


  - job_name: alertmanager

    metrics_path: /alert-manager/metrics

    scrape_interval: 5s

    static_configs:
      - targets:
        - localhost:9093

    relabel_configs:
      - action: replace
        source_labels: ['__address__']
        target_label: node
        regex: ".*"
        replacement: "{{ inventory_hostname_short }}"

  - job_name: node_exporter

    metrics_path: /prom-proxy/9100/metrics

    static_configs:
      - targets:
{% for host in groups['base'] | sort %}
        - prom-{{ host }}
{% endfor %}

    relabel_configs:
      # generate a nice instance of "foo.goeswhere"
      - action: replace
        source_labels: ['__address__']
        target_label: instance
        regex: "prom-([a-z0-9-]+\\.[a-z0-9-]+)\\.\\w+(:\\d+)?"
        replacement: "${1}"
