- name: setup apt keys
  become: yes
  write_apt_keys: spec={{apt_keys}} exclusive=yes remove=yes
  when: ansible_facts['distribution_major_version'] == '22'

- name: setup apt sources.list
  template:
    src=sources.list.j2
    dest=/etc/apt/sources.list
    backup=yes
  become: yes
  when: ansible_facts['distribution_major_version'] == '22'

- name: setup apt sources.d
  become: yes
  write_apt_sources:
    spec={{apt_sources}}
    exclusive=yes
    remove=yes
  when: ansible_facts['distribution_major_version'] == '22'

- name: packages
  become: yes
  apt:
    name={{item}}
    state=present
    install_recommends=no
  with_items:
    # core things that are missing from some images:
    - libpam-systemd      # enable systemd --user
    - openssh-server      # fixes e.g. sftp being missing
    - procps              # pwdx, pkill, free, etc.
    - psmisc              # killall
    - software-properties-common # fixes ppas
    # ansible/setup helpers:
    - acl                 # for the ansible setfacl stuff
    - git
    - python3-apt
    # to enable the ddebs repo:
    - ubuntu-dbgsym-keyring
    # interactive use helpers:
    - curl
    - ncdu
    - tmux
    - zsh
